Fix logic for replaygain auto-compute on import
beetbox/beets pull request #3816
Opened 2020-12-20 18:42 UTC by ybnd

## Description

Fixes #3815.

Apparently I forgot to actually check with the configuration when handling import tasks.

2020-12-20 20:18 UTC, sampsyo requested changes
Awesome; thanks for tracking this down! Just one tiny thing that could be shorter marked within.

2020-12-20 21:30 UTC, skapazzo commented
This seems to write the replaygain metadata in the source file and not the imported file, I'll do some more testing on a fresh install to be sure.

2020-12-20 22:19 UTC, wisp3rwind commented
> ~This seems to write the replaygain metadata in the source file and not the imported file, I'll do some more testing on a fresh install to be sure.~ Disregard that, something weird going on in my testing setup. Everything seems to be ok in a clean environment.

I don't know the replaygain code at all, so I may be wrong, but a brief look at the code suggests a possibly fundamental issue with the parallel workers: Since all work is queued for async execution, and completion is handled in a callback, the replaygain plugin stage in the importer will finish before the replaygain calculation does. Then, while the latter still runs, the following stages, i.e. more plugin stages and most importantly the `manipulate_files` stage, can already execute. This is happening in the "full log" in https://github.com/beetbox/beets/issues/3815.

If that happens (timing might not always be such that this is the case), any `Item` and `Album` objects that the plugin holds in the callback's closure might become stale, which could explain why the source files would be modified, since `manipulate_files` is where the `Item`s' path actually changes.

A quick fix could be reloading items from the database before storing replaygain values and writing tags.

More fundamentally, I don't know of any other importer stage that would complete while still running work in the background. (The convert import stage doesn't, as far as I can tell.) That probably entails quite some risk for data races, so I'm not sure that this is something we want to do.
<del>Changing that without losing parallelism _across_ albums might be impossible without a substantial rework of beets' importer pipeline, though.</del> Actually, I think a stage in beets pipeline can have multiple workers processing distinct tasks. Using that and having the plugin stage wait for replaygain calculation to complete should be the proper fix.

2020-12-20 22:24 UTC, wisp3rwind commented
Could this also explain https://github.com/beetbox/beets/issues/3809 ? Maybe the database is already torn down when store is called? Which raises the question why the second store appears to succeed, though...

2020-12-21 08:11 UTC, ybnd commented
@sampsyo Ooh, I didn't even know about that, thanks!

@wisp3rwind That's an issue alright :open_mouth:. I've replied in a Zulip thread.

2020-12-21 13:47 UTC, sampsyo approved these changes
Thanks!!

2020-12-21 13:48 UTC, merged