Fix: Crash when search encounters a 404 error
beetbox/beets pull request #4413
Opened 2022-07-12 14:18 UTC by arsaboo

Fixes #4411

I had to add a few additional several guard clauses to prevent errors. 

Tested this fix with the same track with both Spotify and MB match and it works fine.

2022-07-14 21:07 UTC, sampsyo commented
Hi! I'm not entirely sure why the `plugins.py` changes are necessary here. It looks like the main change in the plugin is that `_search_api` can now return `None`, but the only place where that function is called is here:
https://github.com/beetbox/beets/blob/7209c5f922ad7bcc9ae88991e1c5cf5494a02577/beetsplug/spotify.py#L524-L527

…which already has a handler for the case where the return value is empty. Any chance you could explain a little more what necessitated the extra `is not None` checks?

2022-07-14 23:16 UTC, arsaboo commented
Without those `None` checks in the plygins.py, we get `NoneType` errors. 
You can try running the code until this [85e58d4](https://github.com/beetbox/beets/pull/4413/commits/85e58d48a26463f0f370f5f051f65bb9451431af) commit and you will see those errors. Consider the following: https://github.com/beetbox/beets/blob/7209c5f922ad7bcc9ae88991e1c5cf5494a02577/beets/plugins.py#L752

My guess is that some of the other plugins (maybe MB) return `None`, causing the error. The same is the case in other places. 
In any case, I don't see a downside in adding those checks.

2022-07-14 23:26 UTC, sampsyo commented
Is there any chance you could include a traceback? Even if the MusicBrainz backend sometimes returns None, I am not seeing how that would be affected by the current change… it would be great to understand what's going on.

2022-07-15 00:59 UTC, arsaboo commented
Here's the trace with plugins.py reverted:
```
Traceback (most recent call last):
  File "/home/arsaboo/.local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/ui/__init__.py", line 1304, in main
    _raw_main(args)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/ui/__init__.py", line 1291, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/ui/commands.py", line 1034, in import_func
    import_files(lib, paths, query)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/ui/commands.py", line 974, in import_files
    session.run()
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/util/pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/util/pipeline.py", line 314, in run
    for msg in _allmsgs(out):
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/util/pipeline.py", line 467, in pull
    out = coro.send(msg)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/util/pipeline.py", line 193, in coro
    func(*(args + (task,)))
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/importer.py", line 1376, in lookup_candidates
    task.lookup_candidates()
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/importer.py", line 913, in lookup_candidates
    prop = autotag.tag_item(self.item, search_ids=self.search_ids)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/autotag/match.py", line 518, in tag_item
    for track_info in hooks.item_candidates(item, search_artist, search_title):
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/plugins.py", line 573, in decorated
    for v in generator(*args, **kwargs):
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/autotag/hooks.py", line 647, in item_candidates
    yield from plugins.item_candidates(item, artist, title)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/plugins.py", line 392, in item_candidates
    yield from plugin.item_candidates(item, artist, title)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/beets/plugins.py", line 752, in item_candidates
    return [self.track_for_id(track_data=track) for track in tracks]
TypeError: 'NoneType' object is not iterable
```
If I fix that we get error on another line.

2022-07-15 12:49 UTC, sampsyo requested changes
Aha; sorry, I feel dumb! I didn't realize that `_search_api` was called within the `MetadataSourcePlugin` base class:
https://github.com/beetbox/beets/blob/7209c5f922ad7bcc9ae88991e1c5cf5494a02577/beets/plugins.py#L732

We will want this plugin to return an _empty list of results_ instead of `None`. That should avoid the `None` special-casing.

2022-07-15 12:49 UTC, sampsyo commented on beetsplug/spotify.py
> +            return None
This should return an empty sequence, i.e., `[]`.

2022-07-15 14:29 UTC, arsaboo commented
The empty sequence helps....it works now 👍

2022-07-15 14:58 UTC, sampsyo approved these changes
LGTM; thanks!

2022-07-15 14:58 UTC, merged