Fix convert plugin attempting to process a non-media file
beetbox/beets pull request #5261
Opened 2024-05-25 10:27 UTC by pierreay

## Description

My library is managed using Beets for organization and [git-annex](https://git-annex.branchable.com/) as storage backend. Therefore when using this system, while my library files always exists on my filesystem, some files may be empty (without content). In this case, when I'm running the `convert` plugin,  I don't wants it to process files which are empty (same apply for any Beets plugin). Hence, I added a check that the file is readable as a `MediaFile` before doing any process. 

Before this fix, trying to encode an empty file would have lead to an error  while leaving `convert` doing its side-effects **and** `convert` would also copy empty files to destination for files that doesn't need to be re-encoded.

In my case, this is empty files, but the problem can be anything else (depending on the storage backend) and/or corrupted files. Conclusion, I think **checking that the file is readable is always recommended before proceeding to heavy operation** like this.

## To Do

- [X] Documentation. (If you've added a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [X] Changelog. (Add an entry to `docs/changelog.rst` to the bottom of one of the lists near the top of the document.)
- [X] Tests. (Very much encouraged but not strictly required.)

2024-06-25 04:22 UTC, Serene-Arc requested changes

2024-06-27 07:14 UTC, pierreay commented on beetsplug/convert.py
> +                mf = mediafile.MediaFile(util.syspath(item.path))
You're right! I'll fix it.

2025-02-06 15:00 UTC, pierreay commented
Hello, kind reminder, is there anything that I can do on my side to see this PR being merged? :)

2025-02-20 03:52 UTC, snejus approved these changes
Looks good - just needs rebasing on master

2025-02-20 16:23 UTC, merged