Ftintitle keep artist
beetbox/beets pull request #5356
Opened 2024-07-10 17:13 UTC by klb2

## Description

This PR adds a new option `keep_in_artist` to the `ftintitle` plugin.

### Previous Behavior
The artist field is _always_ changed to match the albumartist field.  

### New Behavior
The new option allows a customization of the old behavior. If the option is set to yes/true, the "feat. X" part is kept in the artist field.
In order to be backwards compatible and not introduce unexpected behavior, the default is set to false, i.e., matching the old behavior.

### Benefits
- Additional customization
- Searching for features using both title and artist (this can be very helpful when using music players with GUI)

## To Do

- [X] Documentation.
- [X] Changelog.
- [X] Tests.

2024-09-03 05:08 UTC, JOJ0 requested changes
This looks very straight forward. Thanks! I think it doesn't hurt if you also add the typical usecase you mention in the PR description to the docs as well:

> Searching for features using both title and artist (this can be very helpful when using music players with GUI)

Either in the docs introductional text or in the option description itself.

Depending on where you put it, you might want to rephrase. Again just brainstorming here. Something like:

....To be able to search for features in artist fields as well, this option can be used.....

It's helpful in music players that let us search in artist fields in general, not only with GUI.

2024-09-05 10:30 UTC, klb2 commented on beetsplug/ftintitle.py
> +            self._log.info("artist: {0} -> {1}", item.artist, item.artist)
That is a good idea. I have updated the log message.

2024-09-05 10:34 UTC, klb2 reviewed
Looks good to me. Please let me know if you have other change requests

2024-09-05 10:35 UTC, klb2 commented
I have updated the documentation and log message as you have suggested. Please let me know if there are any other changes you would like to see.

2024-09-06 11:40 UTC, JOJ0 approved these changes
Many thanks. This is good to go 🎉

2024-09-06 11:40 UTC, JOJ0 commented on beetsplug/ftintitle.py
> +            )
👍Perfect! Thanks!

2024-09-06 11:40 UTC, JOJ0 commented on docs/plugins/ftintitle.rst
> +  Default: ``no``.
Well written. Straight to the point. I like! 😁

2024-09-06 11:41 UTC, merged

2024-09-21 00:17 UTC, chrishoage commented
This PR produces errors for me 

```
Traceback (most recent call last):
  File "/lsiopy/bin/beet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/beets/ui/__init__.py", line 1865, in main
    _raw_main(args)
  File "/lsiopy/lib/python3.12/site-packages/beets/ui/__init__.py", line 1852, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/lsiopy/lib/python3.12/site-packages/beets/ui/commands.py", line 1400, in import_func
    import_files(lib, paths, query)
  File "/lsiopy/lib/python3.12/site-packages/beets/ui/commands.py", line 1331, in import_files
    session.run()
  File "/lsiopy/lib/python3.12/site-packages/beets/importer.py", line 360, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/lsiopy/lib/python3.12/site-packages/beets/util/pipeline.py", line 447, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/lsiopy/lib/python3.12/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
          ^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/beets/util/pipeline.py", line 195, in coro
    func(*(args + (task,)))
  File "/lsiopy/lib/python3.12/site-packages/beets/importer.py", line 1668, in plugin_stage
    func(session, task)
  File "/lsiopy/lib/python3.12/site-packages/beets/plugins.py", line 143, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/beetsplug/ftintitle.py", line 122, in imported
    self.ft_in_title(item, drop_feat)
TypeError: FtInTitlePlugin.ft_in_title() missing 1 required positional argument: 'keep_in_artist_field'
```

Line here https://github.com/beetbox/beets/blob/cd360b6a99bef5f8b5e4ffce334e89b580bbd652/beetsplug/ftintitle.py#L122

I am able to reproduce just by running `beets import -q /path/to/music`

2024-09-21 00:56 UTC, klb2 commented
Thank you for spotting this @chrishoage. I have created a PR to fix this (#5433)