Add a quick check for MST Store Python install
beetbox/beets pull request #5470
Opened 2024-10-19 02:37 UTC by arogl

## Description

Quick fix for #5467.

Checks if the path for python is under the windows store folder then error and point the user to the beets [documentation](https://beets.readthedocs.io/en/stable/guides/main.html).

Happy for feedback to improve, but thought it best to exit as early as possible.

## To Do

- [x] Documentation.
- [ ] Changelog.
- [x] Tests.

2024-10-20 16:42 UTC, snejus requested changes

2024-10-20 16:42 UTC, snejus commented on beets/ui/__init__.py
> +            "https://beets.readthedocs.io/en/stable/guides/main.html"
Consider using a single `log.error` call:

```suggestion
            "error: beets is unable to use the Microsoft Store version of "
            "Python. Please install Python from python.org. See "
            "https://beets.readthedocs.io/en/stable/guides/main.html."
```

2024-10-22 09:01 UTC, arogl commented on beets/ui/__init__.py
> +            "https://beets.readthedocs.io/en/stable/guides/main.html"
Updated

2024-11-22 05:04 UTC, snejus commented
Apologies for not addressing this earlier - all looks good, just needs a rebase on latest master.

2024-11-22 05:04 UTC, snejus approved these changes

2024-11-22 08:14 UTC, arogl commented
> Apologies for not addressing this earlier - all looks good, just needs a rebase on latest master.

I believe I have managed a rebase 😃

2024-11-22 13:46 UTC, merged