Improve ListenBrainz error handling and simplify playlist handling
beetbox/beets pull request #5480
Opened 2024-10-25 14:53 UTC by arsaboo

## Description

Fixes #5459

## To Do
- [X] Changelog. (Add an entry to `docs/changelog.rst` to the bottom of one of the lists near the top of the document.)
- [ ] Tests. (Very much encouraged but not strictly required.)

2024-11-10 23:22 UTC, snejus requested changes
I commented under the change that is required to fix #5459.

Could you by any chance submit the rest of the changes in a separate PR as they seem to be a more general refactor?

Also, I suspect you are using black to do auto formatting - note that the max line length is configured as **80** across the project.

This should have been caught by CI, but now I see that `ruff` only  shouts for line lengths longer than 88.

2024-11-10 23:22 UTC, snejus commented on beetsplug/listenbrainz.py
> +            tracks.append(track_dict)
I find the original implementation slightly cleaner to read. Consider something like below
```suggestion
            identifier = track.get("identifier")
            if isinstance(identifier, list):
                identifier = identifier[0]

            tracks.append(
                {
                    "artist": track.get("creator", "Unknown artist"),
                    "identifier": identifier.split("/")[-1],
                    "title": track.get("title"),
                }
            )
```

2024-11-11 01:35 UTC, arsaboo commented
@snejus Made the changes. It looks like the check is failing for unrelated reasons.

2024-11-11 04:28 UTC, arsaboo commented
Tests are not my strong suit unfortunately...

The current version is broken anyways, so I don't think we can be worse off. I'm here in case there are any issues that come up. I use this plugin regularly, so trust me I'll be the first to identify an issue 😜

2024-11-12 16:57 UTC, bal-e reviewed
This is a nice and simple little change, thanks @arsaboo!

2024-11-12 16:57 UTC, bal-e commented on beetsplug/listenbrainz.py
> +        )
Is the intent here to sort everything by date, and between playlists of the same date, to sort by type?  Setting `key=lambda x: (x["date"], x["type"])` would be more explicit and more efficient.

2024-11-12 17:01 UTC, bal-e commented on beetsplug/listenbrainz.py
> +        )
Oh, never mind, I see that sorting one key in reverse might be a bit difficult.

2024-11-13 14:11 UTC, merged