Fix the ``TypeError`` when ``import.set_fields`` is provided non-string values
beetbox/beets pull request #5495
Opened 2024-11-07 04:38 UTC by adamharder3

## Description

Fixes #4840 by converting input values to strings before they are used. Modifies the test cases for ``set_fields`` to appropriately test this behavior.

## To Do

- [x] ~~Documentation~~
- [x] Changelog.
- [x] Tests.

2024-11-10 23:01 UTC, snejus requested changes
Good stuff, thanks! Just a tiny nit in the changelog.

2024-11-10 23:01 UTC, snejus commented on docs/changelog.rst
> +* Fix the ``TypeError`` when ``import.set_fields`` is provided non-string values. :bug:`4840`
```suggestion
* Fix the ``TypeError`` when :ref:`set_fields` is provided non-string values. :bug:`4840`
```

2024-11-11 16:15 UTC, adamharder3 commented
Thanks for the suggestion. I applied the changes accordingly.

2024-11-11 16:51 UTC, snejus approved these changes
Thank you!

2024-11-11 16:52 UTC, merged