Use up-to-date namespace package setup for plugins
beetbox/beets pull request #5505
Opened 2024-11-15 07:01 UTC by snejus

### Description

Refactor `beetsplug` to use native namespace packages by removing `__init__.py`. Update documentation and `setup.cfg` to support namespace packages.

### Changes

- Deleted `beetsplug/__init__.py`.
- Updated `docs/dev/plugins.rst` to reflect namespace package structure.
- Updated `mypy` configuration in `setup.cfg`

### Motivation

Adopt PEP 420 native namespace packages to simplify plugin management and eliminate the need for `__init__.py`.

See https://realpython.com/python-namespace-package.

This setup is backwards-compatible, so plugins using the old pkgutil-based setup will continue working fine.

The advantage with this setup is that external plugins will now be able to import modules from 'beetsplug' package for typing purposes. Previously, mypy could not resolve these modules due to presence of `__init__.py`.

2025-01-28 07:43 UTC, JOJ0 requested changes
Built the docs and read them. I like the "attention" box. Some suggestions within.

What I miss in general in our docs is for plugin developers if there is anything specific they need to do in there pyproject.toml or setup.py files.

I'm not sure but is it enough to do this in a setup.py?

```
packages=find_packages(),
```

Here is some information about it: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages

Should we add the most important parts that need to be in the package config. Maybe only focusing on pyproject.toml and setup.py verisions (I suppose they are the most common) and maybe also link to the above? What do you think? Too much information? Less is more?

2025-01-28 07:43 UTC, JOJ0 commented on docs/dev/plugins.rst
> +.. _Stack Overflow question about namespace packages: https://stackoverflow.com/a/27586272/9582674
Should we better link to the realpython article here?

2025-01-28 07:43 UTC, JOJ0 commented on docs/dev/plugins.rst
> +    file anymore.
If the general info about (current) namespace packages is already explained in the realpython article, maybe here you can point out this chapter of the python docs just to make sure we document everything potentially interesting for plugin developers (and also those who adopt old/orphaned plugins;-)): https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#legacy-namespace-packages

2025-01-28 07:43 UTC, JOJ0 commented on setup.cfg
> +explicit_package_bases = true
LGTM. https://mypy.readthedocs.io/en/stable/config_file.html

2025-01-28 09:41 UTC, snejus commented on docs/dev/plugins.rst
> +.. _Stack Overflow question about namespace packages: https://stackoverflow.com/a/27586272/9582674
Could you share the link? 😅

2025-01-28 17:18 UTC, JOJ0 commented on docs/dev/plugins.rst
> +.. _Stack Overflow question about namespace packages: https://stackoverflow.com/a/27586272/9582674
the one you posted in the pr description 😁 

https://realpython.com/python-namespace-package

2025-01-30 12:00 UTC, snejus commented on docs/dev/plugins.rst
> +.. _Stack Overflow question about namespace packages: https://stackoverflow.com/a/27586272/9582674
🤦🏼 🤦🏼 🤦🏼

2025-01-30 12:35 UTC, snejus commented on docs/dev/plugins.rst
> +.. _Stack Overflow question about namespace packages: https://stackoverflow.com/a/27586272/9582674
Added the link to the realpython article as well!

2025-01-30 12:36 UTC, snejus commented on docs/dev/plugins.rst
> +    file anymore.
Removed most of this section and added links to poetry and setuptools

2025-01-31 07:09 UTC, JOJ0 commented
> I prefer explicit (latter) over implicit. For example in beetcamp the following works fine:
> 
> ```toml
> packages = [{ include = "beetsplug" }]
> ```
> 
> I'm not sure we should include these instructions in the docs since we've got a variety of build tools and each has its own instructions. We haven't got anything special going on here so as long as they somehow include the `beetsplug` directory in their package things will work fine. Addings links to `setuptools` and `poetry` docs is a good idea though!

I agree. Less is more and better maintainable. With these links added I think there is more than enough detailed information for a plugin developer. I rendered the article and it reads very straight forward now. Thanks! Merge it!

2025-02-02 16:32 UTC, merged